language: julia
os:
    - osx
    #   - linux
julia:
    - 0.4
notifications:
    email: false
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia --color=yes -e 'Pkg.clone(pwd()); Pkg.build("EconModels"); Pkg.test("EconModels"; coverage=true)'
branches:
  only:
    - master
after_success:
- julia -e 'cd(Pkg.dir("EconModels")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
